keys:
  - &geng_us age1ghh8t7y7y37apc4xzvxz9t5xf6s82nsc8jlpu7ng3x7200trcy3q6k54cr
  #- &geng_rt age1657463rh8kc5qltu07q2k8u0mmw8re5a7dvj004r8dgnrl45qp4sqkwy2z
creation_rules:
  - path_regex: machines/Genghis/secrets.yaml$
    key_groups:
    - age:
      - *geng_us
        #- *geng_rt
