# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  carapace = {
    pname = "carapace";
    version = "1c34c1c619eee7b447f134e48d2db2d0c4d2beb3";
    src = fetchFromGitHub {
      owner = "carapace-sh";
      repo = "carapace-bin";
      rev = "1c34c1c619eee7b447f134e48d2db2d0c4d2beb3";
      fetchSubmodules = false;
      sha256 = "sha256-yUWhwQ4j3BXxo4YT2xSXaAUlV6W8GyhmVtH1L/KJuPY=";
    };
    date = "2025-04-12";
  };
  headscale-ui = {
    pname = "headscale-ui";
    version = "84aec5f45a64d5537237f2fccdf86581df42726b";
    src = fetchFromGitHub {
      owner = "gurucomputing";
      repo = "headscale-ui";
      rev = "84aec5f45a64d5537237f2fccdf86581df42726b";
      fetchSubmodules = false;
      sha256 = "sha256-dnh0OIsNIe7lHIR6T4TZKtzom3ZUoWTjRgq0pFpxRv8=";
    };
    date = "2025-03-20";
  };
  infuse = {
    pname = "infuse";
    version = "c8fb7397039215e1444c835e36a0da7dc3c743f8";
    src = fetchgit {
      url = "https://codeberg.org/amjoseph/infuse.nix";
      rev = "c8fb7397039215e1444c835e36a0da7dc3c743f8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-N+u3vnK3zyXLUuDj/vr62r9tM7uarhKVCaLHWxjo/YY=";
    };
    date = "2025-02-04";
  };
  mobile-nixos = {
    pname = "mobile-nixos";
    version = "6679fd7a8dd4ccf4aa538b82216723861cfe61a2";
    src = fetchFromGitHub {
      owner = "NixOS";
      repo = "mobile-nixos";
      rev = "6679fd7a8dd4ccf4aa538b82216723861cfe61a2";
      fetchSubmodules = false;
      sha256 = "sha256-BedQ9Z3+nqtp9BRjHjJNPUeLIMVbTsP3Udbz0b1cUn0=";
    };
    date = "2025-04-04";
  };
  sixos = {
    pname = "sixos";
    version = "0936127f11698a00d72b13cf8521d9c43d6d371c";
    src = fetchgit {
      url = "https://codeberg.org/amjoseph/sixos";
      rev = "0936127f11698a00d72b13cf8521d9c43d6d371c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Sn+IEto5iDncIkXpMEhmj/4/Sdx9/sRJSg18Axu435w=";
    };
    date = "2025-04-01";
  };
  snix-cache = {
    pname = "snix-cache";
    version = "8ad3b90a44ad82260a2e2c1874df95da76a9f3fa";
    src = fetchgit {
      url = "https://git.dgnum.eu/DGNum/snix-cache";
      rev = "8ad3b90a44ad82260a2e2c1874df95da76a9f3fa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-VYMOlZtJ9JsIEk1hPGmaRz40ht+TzcJmD+iEuK1cIwQ=";
    };
    date = "2025-04-02";
  };
  tmux-kitty = {
    pname = "tmux-kitty";
    version = "e6969ec4d8c12c76534cc801cea910b55f8eaadc";
    src = fetchFromGitHub {
      owner = "jixiuf";
      repo = "tmux";
      rev = "e6969ec4d8c12c76534cc801cea910b55f8eaadc";
      fetchSubmodules = false;
      sha256 = "sha256-t32ZiAJ1KsBwwsXFKji8RtKG+mm1WP/cQRcwPziqb5k=";
    };
    date = "2025-04-09";
  };
}
